---
name: Markdown Links Validation
on: [push, workflow_dispatch]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repository
        uses: actions/checkout@v4.1.4

      - name: Download .markdownlint.json
        uses: suisei-cn/actions-download-file@15306412d2c75df56b46844362b86b65235b7db1 # v1.4.0
        with:
          url: "https://raw.githubusercontent.com/fharper/gh-configs/main/.markdownlinkcheck.json"

      - name: Validate Links
        uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          config-file: '.markdownlinkcheck.json'
